name: jupyter-napari-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - jupyterlab 
  - jupyter-server-proxy
  - nodejs
  - pip
  - python<3.12
  - pytorch
  - pytorch-cuda=12.1
  - pip:
    - napari[all]==0.4.19
    - git+https://github.com/BIIFSweden/jupyter-xprahtml5-proxy.git
